# Generated by Django 4.1.7 on 2023-03-02 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Music',
            new_name='Report',
        ),
    ]
